"""Turn a ProvisionSpec into reviewable steps, a root script and a config file. Pure functions."""

from __future__ import annotations

import secrets
import shlex
from dataclasses import dataclass, field
from datetime import datetime, timezone

from .. import paths
from . import scram
from .spec import BUILD_CFLAGS, BUILD_PACKAGES, GROUP, PIP_EXTRA_PACKAGES, PIP_OVERRIDES, ProvisionSpec

ROOT, DEV, AGENT = "root", "dev", "agent"


@dataclass
class Step:
    id: str
    phase: int
    actor: str            # root | dev | agent
    title: str
    commands: list[str] = field(default_factory=list)


@dataclass
class Secrets:
    pg_password: str
    admin_password: str

    @classmethod
    def generate(cls) -> "Secrets":
        return cls(pg_password=secrets.token_urlsafe(24), admin_password=secrets.token_urlsafe(18))


def q(value: str) -> str:
    return shlex.quote(value)


def addons_path(spec: ProvisionSpec) -> list[str]:
    result = [f"{spec.root}/odoo/addons"]
    if spec.has_enterprise:
        result.append(f"{spec.root}/enterprise")
    result += [f"{spec.root}/{c.destination}" for c in spec.custom if c.addons]
    return result


def render_conf(spec: ProvisionSpec, sec: Secrets, now: datetime | None = None, addons: list[str] | None = None) -> str:
    stamp = (now or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "[options]",
        f"; Generated by Odoo Dev Panel on {stamp}. Contains passwords: keep mode 0640.",
        "; Password that allows database operations:",
        f"admin_passwd = {sec.admin_password}",
        f"db_host = {spec.pg_host}",
        f"db_port = {spec.pg_port}",
        f"db_user = {spec.run_as}",
        f"db_password = {sec.pg_password}",
        "addons_path = " + ",\n\t".join(addons if addons is not None else addons_path(spec)),
    ]
    if spec.http_port is not None:
        lines.append(f"http_port = {spec.http_port}")
    lines += [f"{key} = {value}" for key, value in spec.config_options.items()]
    return "\n".join(lines) + "\n"


def clone_command(url: str, branch: str | None, dest: str) -> str:
    """Shallow clone, built by the same code as the Git workspace (W12)."""
    from ..git.runner import clone_argv

    return " ".join(q(part) for part in clone_argv(url, dest, branch) if part != "--")


def custom_clone_command(repo, dest: str) -> str:
    """A custom repository: shallow single-branch by default, full history when the profile asks for it."""
    from ..git.runner import clone_argv

    return " ".join(q(part) for part in clone_argv(repo.url, dest, repo.branch, repo.shallow) if part != "--")


def requirements_files(spec: ProvisionSpec) -> list[str]:
    """requirements.txt of Odoo plus the optional ones of custom repos (resolved at run time if present)."""
    return [f"{spec.root}/odoo/requirements.txt"] + [f"{spec.root}/{c.destination}/requirements.txt" for c in spec.custom]


def render_root_script(spec: ProvisionSpec, sec: Secrets) -> str:
    """Bash script that runs as root. Contains a SCRAM verifier, never the plaintext password."""
    verifier = scram.verifier(sec.pg_password)
    role_sql = f'CREATE ROLE "{spec.run_as}" LOGIN CREATEDB PASSWORD \'{verifier}\';'
    alter_sql = f'ALTER ROLE "{spec.run_as}" LOGIN CREATEDB PASSWORD \'{verifier}\';'
    odp = " ".join(q(part) for part in paths.odp_command())
    packages = " ".join(BUILD_PACKAGES)
    return f"""#!/usr/bin/env bash
# Generated by Odoo Dev Panel. Review it, then run it as root (the app asks for your sudo password once).
# Order: packages, Linux user and directories, PostgreSQL role (last), agent. Existing parts are reused.
# Creates Odoo {spec.version}: Linux user {spec.run_as}, {spec.root}, {spec.config_dir}, a PostgreSQL role,
# and starts the agent of {spec.run_as}. It contains a password verifier, not the password.
set -euo pipefail

DEV={q(spec.dev_user)}
RUN_AS={q(spec.run_as)}
ROOT={q(spec.root)}
CONF_DIR={q(spec.config_dir)}

# ODP: lines are read by the app for the receipt: every step started, every resource created or changed.
CREATED=()
CHANGED=()
created() {{ CREATED+=("$1"); echo "ODP:created $1"; }}
changed() {{ CHANGED+=("$1"); echo "ODP:changed $1"; }}
step() {{ echo "ODP:step $1"; }}
report() {{
    status=$?
    if [ "$status" -ne 0 ]; then
        echo "FAILED (exit $status). Created before the failure:" >&2
        if [ "${{#CREATED[@]}}" -eq 0 ]; then echo "  (nothing)" >&2; fi
        for item in "${{CREATED[@]}}"; do echo "  - $item" >&2; done
        for item in "${{CHANGED[@]}}"; do echo "  - changed: $item" >&2; done
        echo "Fix the cause and run provision again: existing parts are reused. To undo instead, remove them by hand." >&2
    fi
}}
trap report EXIT

# Reuse what exists, create what is missing. Nothing existing is deleted or overwritten.
USER_EXISTS=0; if id "$RUN_AS" >/dev/null 2>&1; then USER_EXISTS=1; fi
ROLE_EXISTS=0
if command -v psql >/dev/null 2>&1 && \\
   [ "$(runuser -u postgres -- psql -X -tA -c "select 1 from pg_roles where rolname = '$RUN_AS'")" = 1 ]; then
    ROLE_EXISTS=1
fi
[ "$USER_EXISTS" = 1 ] && echo "note: Linux user $RUN_AS exists: reused"
[ -e "$ROOT" ] && echo "note: $ROOT exists: reused, nothing in it is overwritten"
[ "$ROLE_EXISTS" = 1 ] && echo "note: PostgreSQL role $RUN_AS exists: reused, its password is set to the one in the config"

step packages
echo "== System packages for building Odoo's Python dependencies"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y --no-install-recommends {packages}

step user
echo "== Linux user and group"
ROOT_NEW=0
if [ "$USER_EXISTS" = 0 ]; then
    if [ -e "$ROOT" ]; then
        # Existing directory: create the user without touching it.
        useradd --system --user-group --no-create-home --home-dir "$ROOT" --shell /bin/bash "$RUN_AS"
    else
        useradd --system --user-group --create-home --home-dir "$ROOT" --shell /bin/bash "$RUN_AS"
        ROOT_NEW=1
    fi
    created "Linux user and group $RUN_AS"
fi
if ! id -nG "$RUN_AS" | tr ' ' '\n' | grep -qx {GROUP}; then usermod -aG {GROUP} "$RUN_AS"; changed "$RUN_AS added to group {GROUP}"; fi
if ! id -nG "$DEV" | tr ' ' '\n' | grep -qx "$RUN_AS"; then usermod -aG "$RUN_AS" "$DEV"; changed "$DEV added to group $RUN_AS"; fi

step directories
echo "== Directories (owner: $DEV, group: $RUN_AS, setgid, group-writable)"
if [ "$ROOT_NEW" = 1 ]; then
    # useradd created it owned by the new user: hand it to the dev user (group-writable, setgid)
    chown "$DEV":"$RUN_AS" "$ROOT"
    chmod 2775 "$ROOT"
elif [ ! -e "$ROOT" ]; then
    install -d -m 2775 -o "$DEV" -g "$RUN_AS" "$ROOT"
    created "directory $ROOT"
fi
for d in "$ROOT/odoo" "$ROOT/enterprise" "$ROOT/custom"; do
    if [ ! -e "$d" ]; then install -d -m 2775 -o "$DEV" -g "$RUN_AS" "$d"; created "directory $d"; fi
done
# Configs hold passwords: readable by the run-as group only; setgid gives new configs that group.
if [ ! -e "$CONF_DIR" ]; then install -d -m 2750 -o "$DEV" -g "$RUN_AS" "$CONF_DIR"; created "directory $CONF_DIR"; fi
# Shared uv Pythons: a Python installed by one version user with umask 022 is read-only for the others.
if [ -d {q(spec.python_dir)} ]; then chmod -R g+rwX {q(spec.python_dir)}; fi

step role
echo "== PostgreSQL role $RUN_AS"
if [ "$ROLE_EXISTS" = 1 ]; then
    runuser -u postgres -- psql -v ON_ERROR_STOP=1 -X -q <<'SQL'
{alter_sql}
SQL
    changed "password of PostgreSQL role $RUN_AS set to the one in the config"
else
    runuser -u postgres -- psql -v ON_ERROR_STOP=1 -X -q <<'SQL'
{role_sql}
SQL
    created "PostgreSQL role $RUN_AS"
fi

step agent
echo "== Agent of $RUN_AS (keeps running without sudo afterwards)"
# Ask the agent itself: its systemd unit can stay "running" after the agent ended, because
# KillMode=process leaves the Odoo processes in it.
if {odp} --json agent status -u "$RUN_AS" 2>/dev/null | grep -q '"state": "running"'; then
    echo "agent of $RUN_AS is already running"
elif [ -d /run/systemd/system ] && command -v systemd-run >/dev/null; then
    # Own system service: a desktop logout must not stop the agent or the Odoo processes under it.
    systemd-run --quiet --collect --unit="odp-agent-$RUN_AS-$(date +%s)" --uid="$RUN_AS" \\
        --description="Odoo Dev Panel agent ($RUN_AS)" --property=KillMode=process -- \\
        {odp} agent serve --foreground --socket-dir {q(str(paths.socket_dir()))}
else
    runuser -u "$RUN_AS" -- {odp} agent serve --socket-dir {q(str(paths.socket_dir()))}
fi

step done
echo "== Done"
"""


def build_steps(spec: ProvisionSpec, sec: Secrets) -> list[Step]:
    env_py = f"UV_PYTHON_INSTALL_DIR={q(spec.python_dir)}"
    uv = paths.uv_command()
    venv = f"{spec.root}/venv"
    steps = [
        Step("root-script", 1, ROOT, "Create user, directories, packages, PostgreSQL role and agent (one sudo prompt)",
             ["sudo -A bash <generated root script>"]),
        Step("clone-odoo", 2, DEV, f"Clone Odoo community {spec.odoo_branch}",
             [clone_command(spec.odoo_git, spec.odoo_branch, f"{spec.root}/odoo")]),
    ]
    if spec.enterprise_git:
        steps.append(Step("enterprise", 2, DEV, "Clone Odoo enterprise",
                          [clone_command(spec.enterprise_git, spec.enterprise_branch or f"{spec.version}.0", f"{spec.root}/enterprise")]))
    elif spec.enterprise_archive:
        steps.append(Step("enterprise", 2, DEV, "Extract the enterprise archive",
                          [f"extract {q(spec.enterprise_archive)} into {q(spec.root + '/enterprise')} (a single top-level folder is stripped)"]))
    for repo in spec.custom:
        steps.append(Step(f"custom-{repo.name}", 2, DEV, f"Clone {repo.name} into {repo.destination}",
                          [custom_clone_command(repo, f"{spec.root}/{repo.destination}")]))
    reqs = " ".join(f"-r {q(r)}" for r in requirements_files(spec))
    extra = " ".join(q(p) for p in PIP_EXTRA_PACKAGES)
    override = f"--override {q(spec.root + '/.odp-pip-overrides.txt')} " if PIP_OVERRIDES.get(spec.python) else ""
    steps += [
        Step("python", 3, AGENT, f"Install Python {spec.python} in the shared directory, unless it is there already",
             [f"umask 002; {env_py} {uv} python install --no-bin {spec.python}"]),
        Step("venv", 3, AGENT, "Create the virtual environment (owned by " + spec.run_as + ")",
             [f"{env_py} {uv} venv --python {spec.python} --python-preference only-managed {q(venv)}"]),
        Step("pip", 3, AGENT, "Install Python dependencies",
             [f"CFLAGS={q(BUILD_CFLAGS)} {uv} pip install --python {q(venv + '/bin/python')} {override}{reqs} {extra}  (requirements files that exist)"]),
        Step("config", 4, DEV, f"Write {spec.conf_path} (mode 0640) and the receipt",
             [f"write {q(spec.conf_path)}", f"write {q(spec.receipt_path)}"]),
        Step("verify", 5, AGENT, "Verify the installation",
             [f"{q(venv + '/bin/python')} {q(spec.root + '/odoo/odoo-bin')} --version",
              f"psql -h {spec.pg_host} -p {spec.pg_port} -U {spec.run_as} -d postgres -c 'select 1'  (password from the config)"]),
    ]
    return steps
