"""Y9: optional development tools. debugpy goes into an installation's venv (through its agent, like any package);
node + rtlcss and wkhtmltopdf are system packages, installed by one reviewed root script run with sudo.

wkhtmltopdf has no official build for Ubuntu 24.04/26.04. The app downloads the official jammy build from the
wkhtmltopdf packaging releases, checks its size and SHA256 against the values below, and lets apt install it
(apt resolves its dependencies). A file that does not match is deleted and nothing is installed.
"""

from __future__ import annotations

import asyncio
import hashlib
import os
import shlex
import shutil
import subprocess
import tempfile
import urllib.request
from pathlib import Path

from .. import paths

WKHTML = {
    "version": "0.12.6.1-3",
    "url": "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb",
    "file": "wkhtmltox_0.12.6.1-3.jammy_amd64.deb",
    "size": 17326782,
    "sha256": "4f723b2691ad8638a9df960e0421d346d7315083e3583a334f33362280ddba15",  # computed 2026-10-09
}
TOOLS = ("debugpy", "rtlcss", "wkhtmltopdf")


class ToolError(ValueError):
    pass


def _run(argv: list[str]) -> str | None:
    try:
        out = subprocess.run(argv, capture_output=True, text=True, timeout=10, stdin=subprocess.DEVNULL)
    except (OSError, subprocess.SubprocessError):
        return None
    return (out.stdout or out.stderr).strip() if out.returncode == 0 else None


def status(inst: dict | None = None, which=shutil.which, run=_run) -> list[dict]:
    rows = []
    if inst is not None:
        from . import env as env_mod

        interp = env_mod.interpreter(inst)
        version = env_mod.packages(inst, interp["version"] or interp["built_for"]).get("debugpy")
        rows.append({"tool": "debugpy", "scope": "venv", "installed": version is not None, "version": version,
                     "detail": "in the installation's venv: lets an IDE attach to Odoo"})
    node, rtl = which("node"), which("rtlcss")
    rows.append({"tool": "rtlcss", "scope": "system", "installed": bool(node and rtl),
                 "version": run([rtl, "--version"]) if rtl else None,
                 "detail": "right-to-left CSS for Arabic, Hebrew, Persian, Urdu" + ("" if node else "; node is missing")})
    wk = which("wkhtmltopdf")
    text = run([wk, "--version"]) if wk else None
    patched = bool(text and "patched qt" in text.lower())
    rows.append({"tool": "wkhtmltopdf", "scope": "system", "installed": bool(wk), "version": text, "patched": patched,
                 "detail": "PDF reports" + ("" if not wk or patched else "; this build is not the patched-Qt one Odoo needs")})
    return rows


def rtlcss_script() -> str:
    return """#!/usr/bin/env bash
# Generated by Odoo Dev Panel. Installs Node.js and npm from Ubuntu, then rtlcss from the npm registry.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
echo "== apt-get install nodejs npm"
apt-get update -qq
apt-get install -y -qq nodejs npm
echo "== npm install -g rtlcss"
# apt may have just restarted services (needrestart): name resolution can fail for a moment, so retry
for attempt in 1 2 3; do
    npm install -g rtlcss && break
    [ "$attempt" = 3 ] && exit 1
    echo "npm failed, retrying in 10 s ($attempt/3)"; sleep 10
done
echo "== check"
rtlcss --version
"""


def wkhtml_script(deb: str) -> str:
    return f"""#!/usr/bin/env bash
# Generated by Odoo Dev Panel. Installs the official wkhtmltopdf {WKHTML['version']} build (patched Qt), checked
# by its SHA256 before this script was written. apt installs its dependencies.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
DEB={shlex.quote(deb)}
echo "{WKHTML['sha256']}  $DEB" | sha256sum -c -
echo "== apt-get install $DEB"
apt-get update -qq
apt-get install -y -qq "$DEB"
echo "== check"
wkhtmltopdf --version
"""


def downloads_dir() -> Path:
    return paths.agent_state_dir() / "downloads"


def plan(tool, inst: dict | None = None, processes: list[dict] | None = None, agent_running: bool | None = None) -> dict:
    if tool not in TOOLS:
        raise ToolError(f"tool is one of {', '.join(TOOLS)}")
    if tool == "debugpy":
        if inst is None:
            raise ToolError("debugpy goes into an installation's venv: give the installation root")
        from . import actions

        out = actions.install_plan(inst, processes or [], ["debugpy"], agent_running=agent_running)
        return {**out, "kind": "tool", "tool": "debugpy"}
    checks = []
    if not shutil.which("sudo"):
        checks.append({"id": "sudo", "status": "fail", "detail": "sudo is not installed"})
    if not shutil.which("apt-get"):
        checks.append({"id": "apt", "status": "fail", "detail": "apt-get is missing: only Debian/Ubuntu are supported"})
    if tool == "rtlcss":
        script = rtlcss_script()
        steps = [{"id": "root", "phase": 1, "actor": "root", "title": "apt-get install nodejs npm; npm install -g rtlcss (one sudo prompt)",
                  "commands": ["sudo -A bash <script below>"]}]
    else:
        deb = str(downloads_dir() / WKHTML["file"])
        script = wkhtml_script(deb)
        steps = [
            {"id": "download", "phase": 1, "actor": "dev", "title": f"Download {WKHTML['file']} ({WKHTML['size'] // 1024 // 1024} MiB) and check its SHA256",
             "commands": [f"download {WKHTML['url']} to {deb}", f"sha256 must be {WKHTML['sha256']}"]},
            {"id": "root", "phase": 2, "actor": "root", "title": "apt-get install the checked file (one sudo prompt)",
             "commands": ["sudo -A bash <script below>"]},
        ]
        if os.uname().machine not in ("x86_64", "amd64"):
            checks.append({"id": "arch", "status": "fail", "detail": f"the pinned build is amd64; this machine is {os.uname().machine}"})
    return {"kind": "tool", "tool": tool, "checks": checks, "ok": not any(c["status"] == "fail" for c in checks),
            "steps": steps, "script": script, "packages": [tool]}


async def download(report, opener=urllib.request.urlopen) -> str:
    """Fetch the pinned wkhtmltopdf build to the state folder; delete it unless size and SHA256 match."""
    folder = downloads_dir()
    folder.mkdir(parents=True, exist_ok=True)
    target = folder / WKHTML["file"]
    if target.is_file() and _sha256(target) == WKHTML["sha256"]:
        report({"step": "download", "status": "output", "text": f"{target} is already here and matches"})
        return str(target)

    def fetch() -> None:
        fd, tmp = tempfile.mkstemp(dir=folder, prefix=".download-")
        try:
            with os.fdopen(fd, "wb") as fh, opener(WKHTML["url"], timeout=60) as resp:
                size = 0
                while chunk := resp.read(1 << 16):
                    size += len(chunk)
                    if size > WKHTML["size"]:
                        raise ToolError("the download is larger than the pinned file")
                    fh.write(chunk)
            if os.path.getsize(tmp) != WKHTML["size"] or _sha256(Path(tmp)) != WKHTML["sha256"]:
                raise ToolError("the downloaded file does not match the pinned SHA256; nothing was installed")
            os.chmod(tmp, 0o644)
            os.replace(tmp, target)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise

    report({"step": "download", "status": "output", "text": f"downloading {WKHTML['url']}"})
    await asyncio.to_thread(fetch)
    report({"step": "download", "status": "output", "text": f"SHA256 {WKHTML['sha256']} matches"})
    return str(target)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


async def run_system(p: dict, report, root_runner) -> dict:
    """rtlcss or wkhtmltopdf: optional download, then the root script through ``root_runner(script, report)``."""
    if not p["ok"]:
        raise ToolError("; ".join(c["detail"] for c in p["checks"] if c["status"] == "fail"))
    if p["tool"] == "wkhtmltopdf":
        report({"step": "download", "status": "start", "text": p["steps"][0]["title"]})
        await download(report)
        report({"step": "download", "status": "ok", "text": ""})
    report({"step": "root", "status": "start", "text": "root script (sudo asks for your password once)"})
    with tempfile.TemporaryDirectory() as tmp:
        script = Path(tmp) / f"odp-{p['tool']}.sh"
        script.write_text(p["script"])
        script.chmod(0o600)
        code = await root_runner(str(script), report)
    report({"step": "root", "status": "ok" if code == 0 else "fail", "text": f"exit code {code}"})
    after = {r["tool"]: r for r in status()}.get(p["tool"])
    ok = code == 0 and bool(after and after["installed"]) and (p["tool"] != "wkhtmltopdf" or after.get("patched"))
    return {"kind": "tool", "tool": p["tool"], "exit_code": code, "ok": ok, "status": after}

