[package]
name = "odoo-dev-panel"
version = "0.5.0"
description = "Odoo Dev Panel"
license = "Apache-2.0"
authors = ["Huzaifa Farooq <huzaifa.farooq05@gmail.com>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde_json = "1"

[profile.release]
strip = true
lto = true
